### ISSUE TITLE
数码管显示模块 Digit 错误

### ISSUE THREAD

**Issue by ZhengQuancheng** [StevenBaby/computer#1]
请问这个地方的错误改如何解决
![image](https://user-images.githubusercontent.com/60257763/150533236-67329020-09e5-41b8-89a1-770f62f12c88.png)

**Comment by StevenBaby** [comment]
这个模块里不能直接点击模拟，需要在外部将整个模块连到电路上，ROM 需要连接输入，可以在测试电路中测试。
